openapi: 3.0.0
info:
  title: 'Quic Sync API'
  description: 'Quic Sync API'
  version: '1.0'
paths:
  #Data Types
  /api/v1/inbox/{topic}:
    parameters:
      - in: path
        name: topic
        schema:
          type: string
        required: true
        description: 'Topic you wish to post too'
    post:
      summary: 'Post message to the topic provided'
      description: 'Post message to the topic provided'
      tags:
        - Inbox
      requestBody:
        content:
          application/json:
            schema:
              type: object
          application/xml:
            schema:
              type: object
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        201:
          description: 'Data added to the topic'
  /api/v1/inbox/topics:
    get:
      summary: 'Get list of available topics'
      description: 'Get available topics to post messages too'
      tags:
        - Inbox
      responses:
        200:
          description: 'Returns a list of topics to post to.'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example: 
                - people
                - places
                - things
  /api/v1/inbox/config:
    put:
      summary: 'Upsert a topic configuration'
      description: 'Upsert a topic configuration to connect to a local kafka topic and allow this interface to post to that topic'
      tags:
        - Inbox Config
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Topic-Config'
      responses:
        201:
          description: 'Upserted topic config'
  /api/v1/inbox/config/{topic}:
    parameters:
      - in: path
        name: topic
        schema:
          type: string
        required: true
        description: 'Topic name for the config desired'
    get:
      summary: 'Get Config for a specific inbox topic'
      description: 'Gets config for an inbox topic'
      tags:
        - Inbox Config
      responses:
        200:
          description: 'Data topic info' 
        400:
          description: 'Invalid topic name'
          content:
            application/json:
              example:
                error: Invalid topic name
    delete:
      summary: 'Delete a inbox topic configuration'
      description: 'Deletes a configuration to a local kafka topic will not delete the kafka topic just the ability to post from the interface.'
      tags:
        - Inbox Config
      responses:
        201:
          description: 'Topic config deelte'
        400:
          description: 'Topic name invalid'
          content:
            application/json:
              example: 
                error: Invalid topic name
  /api/v1/outbox/topic-connections:
    get:
      summary: 'Get list of active topic connections to other Quic Sync topics'
      description: 'Provides a list of active topic connections to Quic Sync topics'
      tags:
        - Outbox
      responses:
        200:
          description: 'Sends a list of topic connections'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic-Connection'
  /api/v1/outbox/config/topic-connection:
    put:
      summary: 'Add a topic connection'
      description: 'Add a topic connection to the quic sync server'
      tags:
        - Outbox Config
      responses:
        201:
          description: 'Added topic connection'
        400:
          description: 'Error occured with submitted request'
          content:
            application/json:
              examples:
                Bad Format:
                  value:
                    error: 'Request body was not formated correctly'
                Name Already in Use:
                  value:
                    error: 'Topic connection name supplied is already in use'
  /api/v1/outbox/config/topic-connection/{name}:
    parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
        description: 'Unique name of the topic connection'
    get:
      summary: 'Get topic connection config'
      description: 'Get config of a topic connection corresponding to the suppiled name'
      tags:
        - Outbox Config
      responses:
        200:
          description: 'Returns the topic connection associated with the name provided'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Topic-Connection'
        400:
          description: 'Invalid name provided'
          content:
            application/json:
              example:
                error: 'Subscription Name is invalid'
    delete:
      summary: 'Delete subscription'
      description: 'Deletes a subscription from the quic sync server'
      tags:
        - Outbox Config
      responses:
        201:
          description: 'The subscription was deleted'
        400:
          description: 'Invalid Name provided'
          content:
            application/json:
              example:
                error: 'Subscription Name is invalid'
components:
  schemas:
    Topic-Connection:
      type: object
      properties:
        name:
          type: string
          description: Unique name of the subscription.  Used to enumerate subscriptions.
        local-topic:
          type: string
          description: Name of the local kafka topic that is read for this subscription out to other quic sync servers.
        endpoint:
          type: string
          format: url
          description: Inbox target url that data from the local-topic will be sent to.
    Topic-Config:
      type: object
      properties:
        name:
          type: string
        local-topic:
          type: string
